### ISSUE TITLE
set-env command deprecated

### ISSUE THREAD

**Issue by steven-sheehy** [debianmaster/actions-k3s#3]
Got a warning when using the action:

```
Digest: sha256:0621af1e12b357816c61a62d9389bd6a58117ede7be37ced2ec67b64bdc4c704
Status: Downloaded newer image for rancher/k3s:v1.16.9-k3s1
f122523a040eb106e8514233e32f4deac03e2add805a6e42d6816056ac9d617f
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by debianmaster** [comment]
@steven-sheehy  thanks for pointing this out.
 i will change repo to use new syntax

**Comment by steven-sheehy** [comment]
Any update on a fix and a release? This feature will be deactivated in 3 days.

https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/

**Comment by debianmaster** [comment]
@steven-sheehy i will work on this today.

**Comment by debianmaster** [comment]
@steven-sheehy   issue if fixed.   closing this for. now.
if you see any issue please re-open

https://github.com/debianmaster/actions-k3s/runs/1398898413?check_suite_focus=true
